'use client';

import { motion } from 'framer-motion';
import { Cpu, ArrowLeft, Shield, Swords, Zap, Link2, Trophy, Eye, Ban, Users } from 'lucide-react';
import Link from 'next/link';

const SECTIONS = [
  {
    icon: <Shield className="w-6 h-6 text-primary-400" />,
    title: 'Protocol Terms',
    color: 'primary',
    items: [
      { heading: 'Fair Play Mandate', text: 'All participants must compete using only their own code. External tools, AI assistants, or pre-written solutions are strictly prohibited during active matches.' },
      { heading: 'Account Integrity', text: 'One account per person. Sharing, selling, or transferring accounts results in permanent ban. Your identity is your rank.' },
      { heading: 'Crypto Wagers', text: 'All ETH bets are final once placed on-chain. The platform takes a 2% commission. Disputes are resolved by smart contract logic, not human arbitration.' },
      { heading: 'Data & Privacy', text: 'We store your email, username, and match history. No personal data is sold. Wallet addresses are stored only if you connect MetaMask.' },
    ],
  },
  {
    icon: <Swords className="w-6 h-6 text-secondary-400" />,
    title: 'Arena Ethics',
    color: 'secondary',
    items: [
      { heading: 'No Exploitation', text: 'Exploiting platform bugs, judge vulnerabilities, or network timing to gain advantage is grounds for immediate disqualification and ban.' },
      { heading: 'Tab Switch Policy', text: 'Switching browser tabs during a match triggers a warning on first offence. A second offence results in automatic disqualification.' },
      { heading: 'Respect the Arena', text: 'Harassment, hate speech, or toxic behaviour in any platform communication channel will result in suspension.' },
      { heading: 'Trophy Integrity', text: 'Trophy manipulation via match collusion is detected automatically. Both parties face permanent trophy reset and ban.' },
    ],
  },
];

const FEATURES = [
  { icon: <Zap className="w-5 h-5 text-cyan-400" />, title: 'Real-Time 1v1', text: 'Matched by trophy range. Same problem. First to pass all tests wins.' },
  { icon: <Cpu className="w-5 h-5 text-purple-400" />, title: 'AI-Generated Problems', text: 'Every battle uses a unique problem generated by Lyzr AI, calibrated to your skill level.' },
  { icon: <Link2 className="w-5 h-5 text-blue-400" />, title: 'Web3 Wagers', text: 'Optional ETH bets via Ethereum Sepolia. Smart contract settles instantly — 98% to winner.' },
  { icon: <Trophy className="w-5 h-5 text-yellow-400" />, title: 'Arena Progression', text: 'Climb from Bronze to Diamond. Trophies track your dominance across 5 arenas.' },
  { icon: <Eye className="w-5 h-5 text-green-400" />, title: 'Anti-Cheat', text: 'Tab-switch detection, fullscreen enforcement, and runtime analysis keep battles fair.' },
  { icon: <Ban className="w-5 h-5 text-red-400" />, title: 'Zero Tolerance', text: 'Cheating, collusion, and harassment are met with immediate and permanent action.' },
];

export default function AboutPage() {
  return (
    <div className="min-h-screen bg-[#080b14] text-white overflow-x-hidden">
      {/* Background glows */}
      <div className="fixed inset-0 pointer-events-none">
        <div className="absolute top-0 left-1/4 w-[500px] h-[500px] bg-primary-600/5 rounded-full blur-[150px]" />
        <div className="absolute bottom-0 right-1/4 w-[500px] h-[500px] bg-secondary-600/5 rounded-full blur-[150px]" />
      </div>



      {/* Hero */}
      <section className="relative z-10 text-center py-20 px-8">
        <motion.div initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }}>
          <span className="text-[10px] font-black uppercase tracking-[0.4em] text-primary-500 mb-4 block">The Protocol</span>
          <h1 className="text-5xl md:text-7xl font-black uppercase italic tracking-tighter text-white drop-shadow-[0_0_20px_rgba(255,255,255,0.1)] mb-6">
            How the <span className="text-transparent bg-clip-text bg-gradient-to-r from-primary-400 to-secondary-500">Arena</span> Works
          </h1>
          <p className="text-gray-400 max-w-2xl mx-auto text-base leading-relaxed">
            Code Battle is a 1v1 real-time competitive coding platform. Two players. One problem. No mercy. Here's everything you need to know before you enter.
          </p>
        </motion.div>
      </section>

      {/* Features Grid */}
      <section className="relative z-10 px-8 pb-20 max-w-6xl mx-auto">
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5">
          {FEATURES.map((f, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.08 }}
              className="bg-[#0d1117] border border-[#1e2535] rounded-2xl p-6 hover:border-[#2a3040] transition-all"
            >
              <div className="w-10 h-10 rounded-xl bg-[#080b14] border border-[#1e2535] flex items-center justify-center mb-4">{f.icon}</div>
              <h3 className="text-sm font-black uppercase tracking-wider text-white mb-2">{f.title}</h3>
              <p className="text-xs text-gray-400 leading-relaxed">{f.text}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* Protocol & Ethics */}
      <section className="relative z-10 px-8 pb-24 max-w-6xl mx-auto">
        <div className="grid md:grid-cols-2 gap-8">
          {SECTIONS.map((section, si) => (
            <motion.div
              key={si}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: si * 0.1 }}
              className={`bg-[#0d1117] border rounded-2xl p-8 ${section.color === 'primary' ? 'border-primary-500/20' : 'border-secondary-500/20'}`}
            >
              <div className="flex items-center gap-3 mb-6">
                <div className={`w-10 h-10 rounded-xl flex items-center justify-center ${section.color === 'primary' ? 'bg-primary-900/30 border border-primary-500/20' : 'bg-secondary-900/30 border border-secondary-500/20'}`}>
                  {section.icon}
                </div>
                <h2 className={`text-lg font-black uppercase tracking-widest ${section.color === 'primary' ? 'text-primary-400' : 'text-secondary-400'}`}>{section.title}</h2>
              </div>
              <div className="space-y-5">
                {section.items.map((item, ii) => (
                  <div key={ii} className={`border-l-2 pl-4 ${section.color === 'primary' ? 'border-primary-500/40' : 'border-secondary-500/40'}`}>
                    <p className="text-xs font-black uppercase tracking-wider text-white mb-1">{item.heading}</p>
                    <p className="text-xs text-gray-400 leading-relaxed">{item.text}</p>
                  </div>
                ))}
              </div>
            </motion.div>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="relative z-10 text-center pb-24 px-8">
        <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}>
          <p className="text-gray-500 text-xs uppercase tracking-widest mb-6">Ready to compete?</p>
          <div className="flex gap-4 justify-center">
            <Link href="/signup" className="bg-gradient-to-r from-primary-600 to-primary-400 text-white font-black px-10 py-4 rounded-xl uppercase tracking-widest text-sm shadow-[0_0_20px_rgba(0,242,255,0.3)] hover:shadow-[0_0_30px_rgba(0,242,255,0.5)] transition-all hover:scale-105">
              Enter the Arena
            </Link>
            <Link href="/rankings" className="bg-[#0d1117] border border-[#1e2535] hover:border-[#2a3040] text-gray-400 hover:text-white font-black px-10 py-4 rounded-xl uppercase tracking-widest text-sm transition-all">
              Global Ranks
            </Link>
          </div>
        </motion.div>
      </section>

      {/* Footer */}
      <footer className="relative z-10 border-t border-[#1e2535] px-8 py-8 flex flex-col md:flex-row items-center justify-between gap-4">
        <div className="flex items-center gap-2">
          <div className="w-7 h-7 bg-primary-600/20 rounded-lg border border-primary-500/30 flex items-center justify-center">
            <Cpu className="w-4 h-4 text-primary-500" />
          </div>
          <span className="text-sm font-black uppercase italic tracking-tighter text-gray-500">Code Battle</span>
        </div>
        <div className="flex items-center gap-2">
          <div className="w-1.5 h-1.5 bg-green-500 rounded-full animate-pulse" />
          <span className="text-[10px] font-black uppercase tracking-widest text-green-500">All Systems Operational</span>
        </div>
        <p className="text-[10px] font-bold uppercase tracking-widest text-gray-700">© {new Date().getFullYear()} Code Battle Arena. All Protocols Secured.</p>
      </footer>
    </div>
  );
}
